env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  freebsd_instance:
    matrix:
      image: freebsd-12-0-release-amd64
      image: freebsd-11-2-release-amd64
  install_script:
    - pkg install -y git cmake python37 bison autotools textproc/flex
  script:
    - ln -sf /usr/local/bin/python3.7 /usr/local/bin/python3
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/bin
    - echo "using: make -j"`sysctl -n kern.smp.cpus`
    - make -j`sysctl -n kern.smp.cpus`

